extends: spectral:oas
rules:
  # Ensure all operations have tags
  operation-tags: error
  
  # Ensure all operations have operation IDs
  operation-operationId: error
  
  # Ensure responses have descriptions
  operation-description: warn
  
  # Ensure all parameters have descriptions
  operation-parameters: warn
  
  # Ensure all schemas have descriptions
  oas3-schema: warn
  
  # Ensure examples are provided
  operation-examples: warn
  
  # Custom rule: enforce snake_case for property names
  property-names-snake-case:
    description: Property names must use snake_case
    severity: error
    given: $.components.schemas..properties[*]~
    then:
      function: pattern
      functionOptions:
        match: "^[a-z][a-z0-9_]*$"
